from fastapi import APIRouter
import os

router = APIRouter()

# Shared volume path where mock-gpu-node generates keys
KEYS_DIR = "/app/keys"
PRIVATE_KEY_PATH = os.path.join(KEYS_DIR, "demo_id_rsa")


@router.get("/demo")
async def get_demo_connection():
    """
    Returns pre-configured demo connection credentials for mock GPU node.
    This allows users to try the platform without manual SSH setup.
    """
    # Check if running in Docker environment
    demo_available = os.path.exists("/.dockerenv") or os.environ.get("DOCKER_ENV") == "true"
    
    # Also check if keys are available
    keys_ready = os.path.exists(PRIVATE_KEY_PATH)
    
    if not demo_available:
        return {
            "available": False,
            "message": "Demo server not available. Please run with docker-compose."
        }
    
    if not keys_ready:
        return {
            "available": False,
            "message": "Demo keys not ready yet. Please wait for mock-gpu-node to start."
        }
    
    # Return hardcoded demo credentials
    return {
        "available": True,
        "name": "🎮 io-Guard Demo GPU Server",
        "hostname": "mock-gpu-node",
        "username": "root",
        "port": 22,
        "description": "Local Docker container simulating a real GPU server. " +
                      "This container runs in your Docker network and is accessible via SSH, " +
                      "just like a real io.net GPU node. Use it to test deployments safely.",
        "note": "✨ This is a real SSH server (not fake). Copy these credentials " +
               "and use them in the '+ Connect Remote Server' button to practice the workflow.",
        "key_endpoint": "/v1/connections/demo/key"
    }


@router.get("/demo/key")
async def get_demo_private_key():
    """
    Returns the demo private key from the shared volume.
    Keys are auto-generated by mock-gpu-node container at startup.
    No keys are stored in the repository - they are generated at runtime.
    """
    # Check if running in Docker
    if not (os.path.exists("/.dockerenv") or os.environ.get("DOCKER_ENV") == "true"):
        return {
            "error": "Demo only available in Docker environment",
            "available": False
        }
    
    # Check if key file exists
    if not os.path.exists(PRIVATE_KEY_PATH):
        return {
            "error": "Demo keys not ready. Please wait for mock-gpu-node to initialize.",
            "available": False,
            "hint": "Run 'docker-compose up --build' and wait a few seconds."
        }
    
    # Read the private key from shared volume
    try:
        with open(PRIVATE_KEY_PATH, "r") as f:
            demo_key = f.read()
    except Exception as e:
        return {
            "error": f"Failed to read key: {str(e)}",
            "available": False
        }

    return {
        "private_key": demo_key,
        "available": True,
        "note": "This key is auto-generated at container startup. " +
               "It is NOT stored in the repository for security."
    }
