from fastapi import APIRouter
import os

router = APIRouter()

# Shared volume path where mock-gpu-node generates keys

# Internal key path (generated by start.sh)
KEYS_DIR = "/app/keys"
PRIVATE_KEY_PATH = os.path.join(KEYS_DIR, "demo_id_rsa")


@router.get("/demo")
async def get_demo_connection():
    """
    Returns pre-configured demo connection credentials for mock GPU node.
    This allows users to try the platform without manual SSH setup.
    """
    # Check if keys are available
    keys_ready = os.path.exists(PRIVATE_KEY_PATH)
    
    if not keys_ready:
        return {
            "available": False,
            "message": "Demo keys not ready yet. Please wait for backend to initialize."
        }
    
    # Return hardcoded demo credentials for LOCALHOST (Self-SSH)
    return {
        "available": True,
        "name": "🎮 io-Guard Simulation (Internal)",
        "hostname": "127.0.0.1",
        "username": "root",
        "port": 22,
        "description": "Internal SSH server running within the backend container. " +
                      "This simulates a remote GPU node for testing purposes.",
        "note": "✨ This connects to the backend container itself via SSH.",
        "key_endpoint": "/v1/connections/demo/key"
    }


@router.get("/demo/key")
async def get_demo_private_key():
    """
    Returns the demo private key from the local keys directory.
    Keys are auto-generated by start.sh at startup.
    """
    # Check if key file exists
    if not os.path.exists(PRIVATE_KEY_PATH):
        return {
            "error": "Demo keys not ready.",
            "available": False,
            "hint": "Wait a few seconds for start.sh to generate keys."
        }
    
    # Read the private key
    try:
        with open(PRIVATE_KEY_PATH, "r") as f:
            demo_key = f.read()
    except Exception as e:
        return {
            "error": f"Failed to read key: {str(e)}",
            "available": False
        }

    return {
        "private_key": demo_key,
        "available": True,
        "note": "This key is auto-generated at startup."
    }
