-- ==========================================
-- io-Guard v1.5 - Consolidated Supabase Schema
-- ==========================================
-- This file contains the complete schema setup for a fresh Supabase project.
-- Run this in the Supabase SQL Editor to set up the backend.

-- 1. Enable Extensions
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Profiles Table (Hybrid Auth - Linking Supabase Auth to Custom Data)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY, -- Matches auth.users.id if linked, or random UUID for pure custom
  username TEXT UNIQUE NOT NULL,
  credits DECIMAL(10, 2) DEFAULT 0.0,
  password_hash TEXT, -- Storing Bcrypt hash (for local/hybrid fallback)
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Jobs Table (Transaction History & State)
CREATE TABLE IF NOT EXISTS public.jobs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id),
  status TEXT CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')),
  mode TEXT CHECK (mode IN ('SIMULATION', 'LIVE', 'ANALYSIS')),
  gpu_target TEXT,
  final_cost DECIMAL(10, 2),
  logs_summary TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Chat History
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  role TEXT CHECK (role IN ('user', 'assistant')),
  content TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Documents (RAG Knowledge Base with pgvector)
CREATE TABLE IF NOT EXISTS public.documents (
    id TEXT PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    embedding vector(384),  -- all-MiniLM-L6-v2 dimensions
    source TEXT NOT NULL,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for Performance
CREATE INDEX IF NOT EXISTS documents_embedding_idx ON public.documents USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE INDEX IF NOT EXISTS documents_user_idx ON public.documents (user_id);
CREATE INDEX IF NOT EXISTS documents_source_idx ON public.documents (source);
CREATE INDEX IF NOT EXISTS idx_chat_messages_user_id ON public.chat_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_jobs_user_id ON public.jobs(user_id);

-- 6. RPC Function for Semantic Search
CREATE OR REPLACE FUNCTION match_documents(
    query_embedding vector(384),
    match_count INT DEFAULT 5,
    filter_user_id UUID DEFAULT NULL
)
RETURNS TABLE (
    id TEXT,
    content TEXT,
    source TEXT,
    metadata JSONB,
    similarity FLOAT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        d.id,
        d.content,
        d.source,
        d.metadata,
        1 - (d.embedding <=> query_embedding) AS similarity
    FROM public.documents d
    WHERE (filter_user_id IS NULL OR d.user_id = filter_user_id)
    ORDER BY d.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- 7. Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

-- RLS Policies (Simplified for Hackathon / Developer Experience)
-- In production, tighter policies based on auth.uid() = id are recommended.
-- Here we allow 'service_role' (backend) full access and public read (or auth-based).

-- PROFILES
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Service Role has full access profiles" ON public.profiles USING (true) WITH CHECK (true);

-- JOBS
CREATE POLICY "Users view own jobs" ON public.jobs FOR SELECT USING (true); -- Simplification
CREATE POLICY "Service Role full access jobs" ON public.jobs USING (true) WITH CHECK (true);

-- CHAT
CREATE POLICY "Users view own chat" ON public.chat_messages FOR SELECT USING (true);
CREATE POLICY "Service Role full access chat" ON public.chat_messages USING (true) WITH CHECK (true);

-- DOCUMENTS (Strict Owner Access)
CREATE POLICY "Users view own documents" ON public.documents FOR SELECT USING (user_id = auth.uid() OR true); -- 'OR true' strictly for dev ease, remove in prod
CREATE POLICY "Service Role full access documents" ON public.documents USING (true) WITH CHECK (true);

