-- Supabase / Postgres Schema for io-Guard (Hybrid Auth)

-- 1. Profiles Table (Stores User & Credentials)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY, -- Matches Supabase Auth ID if linked, or random UUID for custom
  username TEXT UNIQUE NOT NULL,
  credits DECIMAL(10, 2) DEFAULT 0.0,
  password_hash TEXT, -- Storing Bcrypt hash
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Jobs Table (Transaction History)
CREATE TABLE IF NOT EXISTS jobs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  status TEXT CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')),
  mode TEXT CHECK (mode IN ('SIMULATION', 'LIVE')),
  gpu_target TEXT,
  final_cost DECIMAL(10, 2),
  logs_summary TEXT
);

-- 3. Chat History
CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id),
  role TEXT CHECK (role IN ('user', 'assistant')),
  content TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable RLS (Row Level Security) - Best Practice
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies (Simplified for Hackathon: Open Access for Service Role)
-- You can refine these in the dashboard if needed.
CREATE POLICY "Enable read/write for all" ON profiles FOR ALL USING (true);
CREATE POLICY "Enable read/write for all" ON jobs FOR ALL USING (true);
CREATE POLICY "Enable read/write for all" ON chat_messages FOR ALL USING (true);
